#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GettingStarted.Resource", IsApplication=true)]

namespace GettingStarted
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SatelliteMenu.Resource.Animation.popoutMenuItemAnticipateInterpolator = global::GettingStarted.Resource.Animation.popoutMenuItemAnticipateInterpolator;
			global::SatelliteMenu.Resource.Animation.popoutMenuItemClickAnim = global::GettingStarted.Resource.Animation.popoutMenuItemClickAnim;
			global::SatelliteMenu.Resource.Animation.popoutMenuItemClickInterpolator = global::GettingStarted.Resource.Animation.popoutMenuItemClickInterpolator;
			global::SatelliteMenu.Resource.Animation.popoutMenuItemInRotateInterpolator = global::GettingStarted.Resource.Animation.popoutMenuItemInRotateInterpolator;
			global::SatelliteMenu.Resource.Animation.popoutMenuItemOutRotateInterpolator = global::GettingStarted.Resource.Animation.popoutMenuItemOutRotateInterpolator;
			global::SatelliteMenu.Resource.Animation.popoutMenuItemOvershootInterpolator = global::GettingStarted.Resource.Animation.popoutMenuItemOvershootInterpolator;
			global::SatelliteMenu.Resource.Animation.popoutMenuRotateLeftAnim = global::GettingStarted.Resource.Animation.popoutMenuRotateLeftAnim;
			global::SatelliteMenu.Resource.Animation.popoutMenuRotateRight = global::GettingStarted.Resource.Animation.popoutMenuRotateRight;
			global::SatelliteMenu.Resource.Attribute.closeOnClick = global::GettingStarted.Resource.Attribute.closeOnClick;
			global::SatelliteMenu.Resource.Attribute.itemsAngle = global::GettingStarted.Resource.Attribute.itemsAngle;
			global::SatelliteMenu.Resource.Attribute.mainImage = global::GettingStarted.Resource.Attribute.mainImage;
			global::SatelliteMenu.Resource.Attribute.radius = global::GettingStarted.Resource.Attribute.radius;
			global::SatelliteMenu.Resource.Attribute.speed = global::GettingStarted.Resource.Attribute.speed;
			global::SatelliteMenu.Resource.Id.popoutMenuItem = global::GettingStarted.Resource.Id.popoutMenuItem;
			global::SatelliteMenu.Resource.Layout.popoutMenuItem = global::GettingStarted.Resource.Layout.popoutMenuItem;
			global::SatelliteMenu.Resource.String.empty = global::GettingStarted.Resource.String.empty;
			global::SatelliteMenu.Resource.Styleable.SatelliteMenu = global::GettingStarted.Resource.Styleable.SatelliteMenu;
			global::SatelliteMenu.Resource.Styleable.SatelliteMenu_closeOnClick = global::GettingStarted.Resource.Styleable.SatelliteMenu_closeOnClick;
			global::SatelliteMenu.Resource.Styleable.SatelliteMenu_itemsAngle = global::GettingStarted.Resource.Styleable.SatelliteMenu_itemsAngle;
			global::SatelliteMenu.Resource.Styleable.SatelliteMenu_mainImage = global::GettingStarted.Resource.Styleable.SatelliteMenu_mainImage;
			global::SatelliteMenu.Resource.Styleable.SatelliteMenu_radius = global::GettingStarted.Resource.Styleable.SatelliteMenu_radius;
			global::SatelliteMenu.Resource.Styleable.SatelliteMenu_speed = global::GettingStarted.Resource.Styleable.SatelliteMenu_speed;
			global::Syncfusion.Data.Resource.String.library_name = global::GettingStarted.Resource.String.library_name;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Ascending = global::GettingStarted.Resource.Drawable.Ascending;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Descending = global::GettingStarted.Resource.Drawable.Descending;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.FirstPageIcon = global::GettingStarted.Resource.Drawable.FirstPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.LastPageIcon = global::GettingStarted.Resource.Drawable.LastPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.NextPageIcon = global::GettingStarted.Resource.Drawable.NextPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.PrevPageIcon = global::GettingStarted.Resource.Drawable.PrevPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Sort = global::GettingStarted.Resource.Drawable.Sort;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.SortDescending = global::GettingStarted.Resource.Drawable.SortDescending;
			global::Syncfusion.SfDataGrid.Android.Resource.String.library_name = global::GettingStarted.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int popoutMenuItemAnticipateInterpolator = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int popoutMenuItemClickAnim = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int popoutMenuItemClickInterpolator = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int popoutMenuItemInRotateInterpolator = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int popoutMenuItemOutRotateInterpolator = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int popoutMenuItemOvershootInterpolator = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int popoutMenuRotateLeftAnim = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int popoutMenuRotateRight = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int closeOnClick = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int itemsAngle = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int mainImage = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int radius = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int speed = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Ascending = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bobo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bolaicon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cartoleta = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cartoleta2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Descending = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int escalados = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int FirstPageIcon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icolista = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int LastPageIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int mes = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int NextPageIcon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int person = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int pontape = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int PrevPageIcon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int refre = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int refresh2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int rodada = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Sort = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int SortDescending = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int trofeu64 = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int Relative = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int menu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int popoutMenu = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int popoutMenuItem = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int popoutMenuItem = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int empty = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SatelliteMenu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 3
			public const int SatelliteMenu_closeOnClick = 3;
			
			// aapt resource value: 1
			public const int SatelliteMenu_itemsAngle = 1;
			
			// aapt resource value: 4
			public const int SatelliteMenu_mainImage = 4;
			
			// aapt resource value: 2
			public const int SatelliteMenu_radius = 2;
			
			// aapt resource value: 0
			public const int SatelliteMenu_speed = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
